# Generated by Django 5.2.4 on 2025-07-16 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('employee_id_number', models.CharField(help_text='Unique identifier for the employee', max_length=50, unique=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PPE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Hardhat, Mask, Safety Vest', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('body_temperature', models.DecimalField(decimal_places=2, help_text='Temperature in Celsius', max_digits=4)),
                ('image_attendance', models.CharField(help_text='Path to the photo taken during check-in', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.employee')),
            ],
        ),
        migrations.CreateModel(
            name='PPEDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.attendance')),
                ('ppe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ppe')),
            ],
            options={
                'unique_together': {('attendance', 'ppe')},
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='detected_ppes',
            field=models.ManyToManyField(through='core.PPEDetection', to='core.ppe'),
        ),
    ]
