# Generated by Django 5.2.4 on 2025-07-21 01:08

from django.db import migrations

INITIAL_PPES = [
    'Hardhat',
    'Mask',
    'Safety Vest',
]

def create_initial_ppes(apps, schema_editor):
    PPE = apps.get_model('core', 'PPE')
    for ppe_name in INITIAL_PPES:
        PPE.objects.get_or_create(name=ppe_name)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'), 
    ]

    operations = [
        migrations.RunPython(create_initial_ppes), 
    ]