# Generated by Django 5.2.4 on 2025-07-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20250721_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Hadir', 'Hadir'), ('Izin', 'Izin'), ('Sakit', 'Sakit'), ('Tanpa Keterangan', 'Tanpa Keterangan')], default='Tanpa Keterangan', help_text='Status of attendance', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='image_attendance',
            field=models.ImageField(help_text='Path to the photo taken during check-in', upload_to='attendance_image/'),
        ),
    ]
