# Generated by Django 5.2.4 on 2025-07-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_attendance_status_alter_attendance_image_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='image_attendance',
            field=models.ImageField(blank=True, help_text='Path to the photo taken during check-in', null=True, upload_to='attendance_image/'),
        ),
    ]
