# Generated by Django 5.2.4 on 2025-07-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_attendance_image_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='body_temperature',
            field=models.DecimalField(decimal_places=2, help_text='Temperature in Celsius', max_digits=4, null=True),
        ),
    ]
